# -*- coding: utf-8 -*-
"""
Created on Fri Oct  7 13:20:09 2022

@author: Jesus-Mtz
"""

#ESTO ES UN COMENTARIO
#HOLA ESTOY ESCRIBIENDO UN COMENTARIO EN PYTHON

"""ESTOY COMENTANDO EN MULTIPLES
LINEAS"""

#SFDFSDFSDFSDFSDFSDFQWERFERG